### ISSUE TITLE
那个TXT格式的漫画源我导入不了，有没有JSON格式的？ 谢谢

### ISSUE THREAD

**Issue by SuperBlackWednesday** [entr0pia/MyLegadoSource#1]

**Comment by entr0pia** [comment]
下载下来本地导入

**Comment by SuperBlackWednesday** [comment]
> 下载下来本地导入
我把 https://raw.githubusercontent.com/entr0pia/MyLegadoSource/master/comicSource.txt上面的所有字母都保存在一个txt文件里面 这个TXT文件大小有101KB   然后用阅读3.0保存这个TXT 文件  显示下面内容
rd.g:Unexpected exception java.io.1OException:Stream Closed occur at position -1.
我也尝试网络导入   也显示这个内容
有一个网站 好像过期了 https://github.com/chashaomanhua/manhuadaquan
但是这个页面上我能下载到本地  本地能导入 不过他许多原都不能用了  他是JSON 格式的 如果你搞不了 JSON  能告诉我   我遇到这个代码怎么解决吗？  还是我的使用方式错了？

**Comment by entr0pia** [comment]
我明白你问题在哪儿了, `comicSource.txt`是异次元漫画的源. [阅读]中我没有添加漫画源
